# Alarm design, in one paragraph: `urgent` is "users cannot use the site" —
# no healthy target, no running task, the load balancer answering 5xx itself,
# a dependency the backend cannot reach, a deploy that rolled itself back.
# `informational` is "look at this when you are next at a desk" — the
# backend returning errors, slow responses, a task near its CPU or memory
# ceiling. Every alarm treats missing data as not breaching, because a
# metric that stops arriving is a separate problem with its own alarm
# (RunningTaskCount) and should not fire every other alarm alongside it.

locals {
  alb_dims = { LoadBalancer = var.alb_arn_suffix }

  target_groups = {
    backend  = var.backend_target_group_arn_suffix
    frontend = var.frontend_target_group_arn_suffix
  }

  services = {
    backend  = var.backend_service_name
    frontend = var.frontend_service_name
  }
}

# --- urgent -----------------------------------------------------------------------

resource "aws_cloudwatch_metric_alarm" "unhealthy_targets" {
  for_each = local.target_groups

  alarm_name          = "${var.name_prefix}-${each.key}-unhealthy-targets"
  alarm_description   = "URGENT: a ${each.key} task is failing the load balancer's health check. Runbook: docs/runbooks/site-down.md"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "UnHealthyHostCount"
  statistic           = "Maximum"
  period              = 60
  evaluation_periods  = 2
  threshold           = 1
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = merge(local.alb_dims, { TargetGroup = each.value })

  alarm_actions = [aws_sns_topic.urgent.arn]
  ok_actions    = [aws_sns_topic.urgent.arn]

  tags = { Name = "${var.name_prefix}-${each.key}-unhealthy-targets" }
}

# Container Insights is enabled on the cluster (backend module), which is what
# publishes this metric. Fewer running tasks than one means the service is
# down whatever the health checks say — there is nothing to check.
resource "aws_cloudwatch_metric_alarm" "no_running_tasks" {
  for_each = local.services

  alarm_name          = "${var.name_prefix}-${each.key}-no-running-tasks"
  alarm_description   = "URGENT: the ${each.key} service has no running task. Runbook: docs/runbooks/site-down.md"
  namespace           = "ECS/ContainerInsights"
  metric_name         = "RunningTaskCount"
  statistic           = "Minimum"
  period              = 60
  evaluation_periods  = 3
  threshold           = 1
  comparison_operator = "LessThanThreshold"
  treat_missing_data  = "breaching"

  dimensions = {
    ClusterName = var.cluster_name
    ServiceName = each.value
  }

  alarm_actions = [aws_sns_topic.urgent.arn]
  ok_actions    = [aws_sns_topic.urgent.arn]

  tags = { Name = "${var.name_prefix}-${each.key}-no-running-tasks" }
}

# 5xx generated by the load balancer itself — 502/503/504 because no target
# answered — as opposed to 5xx a target returned. This is "the site is down"
# from the user's point of view.
resource "aws_cloudwatch_metric_alarm" "elb_5xx" {
  alarm_name          = "${var.name_prefix}-alb-5xx"
  alarm_description   = "URGENT: the load balancer is answering 5xx itself, meaning no target is responding. Runbook: docs/runbooks/site-down.md"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_ELB_5XX_Count"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = 5
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = local.alb_dims

  alarm_actions = [aws_sns_topic.urgent.arn]
  ok_actions    = [aws_sns_topic.urgent.arn]

  tags = { Name = "${var.name_prefix}-alb-5xx" }
}

# The backend logs every failed readiness check as a JSON line
# ({"kind":"readiness","check":"database","ok":false,...}, docs/observability.md).
# Counting those lines is how "Supabase or S3 is unreachable" becomes an
# alarm without the load balancer ever polling /ready — which it must not,
# for the reason the backend module's README gives.
resource "aws_cloudwatch_log_metric_filter" "readiness_failures" {
  name           = "${var.name_prefix}-readiness-failures"
  log_group_name = var.backend_log_group_name
  pattern        = "{ $.kind = \"readiness\" && $.ok is false }"

  metric_transformation {
    name          = "ReadinessFailures"
    namespace     = var.name_prefix
    value         = "1"
    default_value = "0"
    unit          = "Count"
  }
}

resource "aws_cloudwatch_metric_alarm" "readiness_failures" {
  alarm_name          = "${var.name_prefix}-backend-readiness"
  alarm_description   = "URGENT: the backend cannot reach a dependency (database or storage). The failing check is named in the log group. Runbook: docs/runbooks/database-unreachable.md or storage-failure.md, by the check field"
  namespace           = var.name_prefix
  metric_name         = "ReadinessFailures"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = var.readiness_failures_per_5m
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"

  alarm_actions = [aws_sns_topic.urgent.arn]
  ok_actions    = [aws_sns_topic.urgent.arn]

  tags = { Name = "${var.name_prefix}-backend-readiness" }

  depends_on = [aws_cloudwatch_log_metric_filter.readiness_failures]
}

# A deploy whose new tasks never became healthy: the circuit breaker rolled
# the service back to the previous task definition. The site is up, on the
# old code, and somebody needs to know the release did not land.
resource "aws_cloudwatch_event_rule" "deployment_failed" {
  name        = local.deployment_failed_rule_name
  description = "ECS deployment circuit breaker rolled a service back"

  event_pattern = jsonencode({
    source      = ["aws.ecs"]
    detail-type = ["ECS Deployment State Change"]
    detail = {
      eventName  = ["SERVICE_DEPLOYMENT_FAILED"]
      clusterArn = [var.cluster_arn]
    }
  })

  tags = { Name = local.deployment_failed_rule_name }
}

resource "aws_cloudwatch_event_target" "deployment_failed" {
  rule      = aws_cloudwatch_event_rule.deployment_failed.name
  target_id = "urgent-topic"
  arn       = aws_sns_topic.urgent.arn

  input_transformer {
    input_paths = {
      service = "$.resources[0]"
      reason  = "$.detail.reason"
    }
    input_template = "\"URGENT: an ECS deployment failed and was rolled back. Service: <service>. Reason: <reason>. Runbook: docs/runbooks/deploy-rolled-back.md\""
  }
}

# --- informational ---------------------------------------------------------------

resource "aws_cloudwatch_metric_alarm" "backend_5xx" {
  alarm_name          = "${var.name_prefix}-backend-5xx"
  alarm_description   = "The backend returned ${var.backend_5xx_per_5m} or more 5xx responses in five minutes. Runbook: docs/runbooks/backend-errors.md"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_Target_5XX_Count"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = var.backend_5xx_per_5m
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = merge(local.alb_dims, { TargetGroup = var.backend_target_group_arn_suffix })

  alarm_actions = [aws_sns_topic.informational.arn]
  ok_actions    = [aws_sns_topic.informational.arn]

  tags = { Name = "${var.name_prefix}-backend-5xx" }
}

resource "aws_cloudwatch_metric_alarm" "backend_latency" {
  alarm_name          = "${var.name_prefix}-backend-latency"
  alarm_description   = "Backend p95 response time over ${var.backend_p95_latency_seconds}s for fifteen minutes. Runbook: docs/runbooks/backend-errors.md"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "TargetResponseTime"
  extended_statistic  = "p95"
  period              = 300
  evaluation_periods  = 3
  threshold           = var.backend_p95_latency_seconds
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = merge(local.alb_dims, { TargetGroup = var.backend_target_group_arn_suffix })

  alarm_actions = [aws_sns_topic.informational.arn]
  ok_actions    = [aws_sns_topic.informational.arn]

  tags = { Name = "${var.name_prefix}-backend-latency" }
}

# Sustained high CPU on a service that autoscales means it is at its ceiling;
# sustained high memory means the next LibreOffice conversion may be the one
# that gets the task killed. Neither is an outage; both want a look.
resource "aws_cloudwatch_metric_alarm" "service_cpu" {
  for_each = local.services

  alarm_name          = "${var.name_prefix}-${each.key}-cpu-high"
  alarm_description   = "The ${each.key} service has averaged over 85% CPU for fifteen minutes. Runbook: docs/runbooks/high-resource-usage.md"
  namespace           = "AWS/ECS"
  metric_name         = "CPUUtilization"
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 3
  threshold           = 85
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    ClusterName = var.cluster_name
    ServiceName = each.value
  }

  alarm_actions = [aws_sns_topic.informational.arn]
  ok_actions    = [aws_sns_topic.informational.arn]

  tags = { Name = "${var.name_prefix}-${each.key}-cpu-high" }
}

resource "aws_cloudwatch_metric_alarm" "service_memory" {
  for_each = local.services

  alarm_name          = "${var.name_prefix}-${each.key}-memory-high"
  alarm_description   = "The ${each.key} service has averaged over 85% memory for fifteen minutes. Runbook: docs/runbooks/high-resource-usage.md"
  namespace           = "AWS/ECS"
  metric_name         = "MemoryUtilization"
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 3
  threshold           = 85
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    ClusterName = var.cluster_name
    ServiceName = each.value
  }

  alarm_actions = [aws_sns_topic.informational.arn]
  ok_actions    = [aws_sns_topic.informational.arn]

  tags = { Name = "${var.name_prefix}-${each.key}-memory-high" }
}
